from . import hr_employee
from . import hr_leave
from . import hr_leave_allocation
from . import hr_leave_type
from . import hr_leave_report
from . import hr_leave_entitled
from . import hr_leave_history
from . import hr_job
from . import res_company
