from . import account_asset
from . import account_invoice
from . import res_config_settings
from . import asset_accountability_transfer
from . import account_move
from . import stock_move_line
from . import stock_production_lot
from . import product_template
from . import outlet_opening_checklist
